#!/usr/bin/env python3
"""Build per-game Ludusavi secondary manifests for emulator saves.

Every path is relative to <root>: add each emulator's data folder to Ludusavi as
an "other" root (see README). One output file per emulator in manifests/.
Standard library only.
"""
import html
import json
import os
import re
import sys
import unicodedata
import urllib.parse
import urllib.request
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, ".cache")
OUT = os.path.join(HERE, "manifests")
LIBRETRO = "https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/"

SOURCES = {
    "ps2": "https://raw.githubusercontent.com/PCSX2/pcsx2/master/bin/resources/GameIndex.yaml",
    "tdb": "https://raw.githubusercontent.com/dolphin-emu/dolphin/master/Data/Sys/wiitdb-en.txt",
    "3ds_US": "https://raw.githubusercontent.com/hax0kartik/3dsdb/master/jsons/list_US.json",
    "3ds_GB": "https://raw.githubusercontent.com/hax0kartik/3dsdb/master/jsons/list_GB.json",
    "3ds_JP": "https://raw.githubusercontent.com/hax0kartik/3dsdb/master/jsons/list_JP.json",
}
PSP_DATS = ["no-intro/Sony - PlayStation Portable.dat", "no-intro/Sony - PlayStation Portable (PSN).dat",
            "redump/Sony - PlayStation Portable.dat"]
# ROM-name databases for systems played through RetroArch cores.
RETROARCH_DATS = [
    "no-intro/Atari - 2600.dat", "no-intro/Atari - 7800.dat", "no-intro/Atari - Lynx.dat",
    "no-intro/Bandai - WonderSwan.dat", "no-intro/Bandai - WonderSwan Color.dat",
    "no-intro/NEC - PC Engine - TurboGrafx 16.dat", "no-intro/NEC - PC Engine SuperGrafx.dat",
    "no-intro/Nintendo - Family Computer Disk System.dat", "no-intro/Nintendo - Game Boy.dat",
    "no-intro/Nintendo - Game Boy Color.dat", "no-intro/Nintendo - Game Boy Advance.dat",
    "no-intro/Nintendo - Nintendo 64.dat", "no-intro/Nintendo - Nintendo DS.dat",
    "no-intro/Nintendo - Nintendo DSi.dat", "no-intro/Nintendo - Nintendo Entertainment System.dat",
    "no-intro/Nintendo - Pokemon Mini.dat", "no-intro/Nintendo - Super Nintendo Entertainment System.dat",
    "no-intro/Nintendo - Virtual Boy.dat", "no-intro/SNK - Neo Geo Pocket.dat",
    "no-intro/SNK - Neo Geo Pocket Color.dat", "no-intro/Sega - 32X.dat", "no-intro/Sega - Game Gear.dat",
    "no-intro/Sega - Master System - Mark III.dat", "no-intro/Sega - Mega Drive - Genesis.dat",
    "no-intro/Sega - SG-1000.dat", "no-intro/Sony - PlayStation Portable.dat",
    "redump/NEC - PC Engine CD - TurboGrafx-CD.dat", "redump/Sega - Dreamcast.dat",
    "redump/Sega - Mega-CD - Sega CD.dat", "redump/Sega - Saturn.dat", "redump/Sony - PlayStation.dat",
]


def fetch(key, url):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, re.sub(r"[^A-Za-z0-9.]+", "_", key))
    if not os.path.exists(path):
        print(f"fetch {url}", file=sys.stderr)
        with urllib.request.urlopen(urllib.parse.quote(url, safe=":/")) as r, open(path, "wb") as f:
            f.write(r.read())
    return open(path, encoding="utf-8", errors="replace").read()


def dat(rel):
    return fetch(rel, LIBRETRO + rel)


def clean(name):
    """Tidy a database title into a display name."""
    name = html.unescape(re.sub(r"<br\s*/?>", " ", name))
    name = re.sub(r"[™®©]", "", name)
    return re.sub(r"\s+", " ", unicodedata.normalize("NFC", name)).strip()


def strip_tags(name):
    """'Game (USA) (Rev 1) [b]' -> 'Game'."""
    return re.sub(r"(\s*[(\[][^)\]]*[)\]])+\s*$", "", name).strip() or name


def glob_escape(s):
    return re.sub(r"([\[\]*?{}])", r"[\1]", s)


def write(emulator, games, header):
    path = os.path.join(OUT, f"{emulator}.yaml")
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by generate.py - do not edit. {header}\n---\n")
        for name in sorted(games):
            f.write(f"{json.dumps(name, ensure_ascii=False)}:\n  files:\n")
            for p in sorted(games[name]):
                f.write(f"    {json.dumps(p, ensure_ascii=False)}:\n      tags:\n        - save\n")
    print(f"{emulator}: {len(games)} games, {sum(map(len, games.values()))} paths", file=sys.stderr)


def pcsx2():
    """Root = PCSX2 memcards folder holding a *folder* memory card."""
    games = defaultdict(set)
    serial = None
    names = {}
    for line in fetch("ps2", SOURCES["ps2"]).splitlines():
        m = re.match(r"^([A-Z]{4}-\d{5}):", line)
        if m:
            serial = m.group(1)
            continue
        m = re.match(r'^  (name|name-en): "(.*)"\s*$', line)
        if m and serial and (m.group(1) == "name-en" or serial not in names):
            names[serial] = m.group(2).replace('\\"', '"')
    for serial, name in names.items():
        games[f"{clean(name)} (PS2)"].add(f"<root>/*/B?{serial}*")
    games["PCSX2 (system)"].update({"<root>/*/BADATA-SYSTEM", "<root>/*/_pcsx2_superblock"})
    write("pcsx2", games, "Source: PCSX2 GameIndex.yaml")


def dolphin():
    """Root = Dolphin user folder (contains GC/, Wii/, StateSaves/). GCI-folder cards only."""
    games = defaultdict(set)
    for line in fetch("tdb", SOURCES["tdb"]).splitlines():
        m = re.match(r"^([A-Z0-9]{4})([A-Z0-9]{2}) = (.+)$", line)
        if not m or line.startswith("TITLES"):
            continue
        code, maker, name = m.group(1), m.group(2), clean(m.group(3))
        gc = code[0] in "GDP"
        wii = code[0] not in "GD"
        label = "GameCube" if code[0] in "GD" else "Wii"
        key = f"{name} ({label})"
        games[key].add(f"<root>/StateSaves/{code}{maker}.*")
        if gc:
            games[key].add(f"<root>/GC/*/*/{maker}-{code}-*.gci")
        if wii:
            games[key].add(f"<root>/Wii/title/00010000/{code.encode().hex()}")
    games["Dolphin (system)"].update({"<root>/GC/SRAM.raw", "<root>/Wii/shared2/sys/SYSCONF", "<root>/Wii/fst.bin"})
    write("dolphin", games, "Source: GameTDB via Dolphin wiitdb-en.txt")


def azahar():
    """Root = Azahar/Citra user folder (contains sdmc/, nand/)."""
    games = defaultdict(set)
    seen = {}
    for region in ("US", "GB", "JP"):
        for x in json.loads(fetch(f"3ds_{region}", SOURCES[f"3ds_{region}"])):
            tid = x.get("TitleID", "").lower()
            if not tid.startswith("00040000") or tid in seen:
                continue
            seen[tid] = name = clean(x.get("Name", "")) or tid
            low = tid[8:]
            key = f"{name} (3DS)"
            games[key].add(f"<root>/sdmc/Nintendo 3DS/*/*/title/00040000/{low}")
            games[key].add(f"<root>/sdmc/Nintendo 3DS/*/*/extdata/00000000/{int(low, 16) >> 8:08X}")
    games["Azahar (system)"].update({"<root>/nand", "<root>/sysdata"})
    write("azahar", games, "Source: hax0kartik/3dsdb")


def ppsspp():
    """Root = PPSSPP's PSP folder (contains SAVEDATA/, PPSSPP_STATE/)."""
    games = defaultdict(set)
    for rel in PSP_DATS:
        for block in dat(rel).split("\ngame (")[1:]:
            n = re.search(r'name "([^"]+)"', block)
            for a, b in set(re.findall(r'serial "([A-Z]{4})-?(\d{5})"', block)):
                key = f"{clean(strip_tags(n.group(1)))} (PSP)"
                games[key].add(f"<root>/SAVEDATA/{a}{b}*")
                games[key].add(f"<root>/PPSSPP_STATE/{a}{b}_*")
    write("ppsspp", games, "Source: libretro-database PSP DATs")


def retroarch(aliases):
    """Root = RetroArch config folder (contains saves/, states/), sorted by core or not."""
    games = defaultdict(set)

    def add(key, stem):
        s = glob_escape(stem)
        for kind in ("saves", "states"):
            games[key].add(f"<root>/{kind}/**/{s}.*")
            games[key].add(f"<root>/{kind}/**/{s} (*")

    for rel in RETROARCH_DATS:
        for name in re.findall(r'\ngame \(\s*name "([^"]+)"', dat(rel)):
            title = strip_tags(name)
            if len(title) >= 2:
                add(f"{clean(title)} (RetroArch)", title)
    # aliases: file-name title -> canonical title (merge) or null (standalone entry)
    for stem, target in aliases.items():
        add(f"{clean(target or stem)} (RetroArch)", stem)
    write("retroarch", games, "Source: libretro-database No-Intro/Redump DATs + aliases.json")


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    aliases = json.load(open(os.path.join(HERE, "aliases.json"), encoding="utf-8"))
    pcsx2()
    dolphin()
    azahar()
    ppsspp()
    retroarch(aliases.get("retroarch", {}))
